# Doom Emacs store-built DOOMDIR builder.
#
# Curried over core's pinned `inputs` and nixpkgs `lib`, then becomes a
# flake-parts module that registers `mkDoomdir` on `config.flake.lib`
# (auto-discovered from `lib/` by the framework).
#
# Composes a read-only `$DOOMDIR` from core's shared doom tree plus a leaf
# overlay, materializing it as a single store path that `~/.config/doom`
# symlinks to. Identity is injected via a generated `identity.el` built from a
# minimal `mine.*` evaluation (not a full host eval).
{ inputs, lib }:
_:
let
  # Two-pass identity extraction: leaf `identity.nix` files may set `mine.*`
  # options declared outside `modules/options.nix` (e.g. a leaf system module),
  # so a straight `evalModules [ options.nix ] ++ identity` would fail on
  # undefined options. First capture the raw `mine` value against a permissive
  # attrset, then prune it to the options `options.nix` actually declares
  # (reusing the same prune logic the Home Manager mirror uses).
  rawMine =
    identity:
    (lib.evalModules {
      modules = [
        {
          options.mine = lib.mkOption {
            type = lib.types.lazyAttrsOf lib.types.raw;
            default = { };
          };
        }
      ]
      ++ identity;
    }).config.mine;

  resolvedMine =
    identity:
    (lib.evalModules {
      modules = [
        # options.nix writes `config.assertions` and (conditionally)
        # `config.warnings`; declare them so the standalone eval has somewhere to
        # put them (NixOS/HM declare them in their own module systems, but this
        # mini-eval does not).
        {
          options.assertions = lib.mkOption {
            type = lib.types.listOf lib.types.raw;
            default = [ ];
          };
          options.warnings = lib.mkOption {
            type = lib.types.listOf lib.types.raw;
            default = [ ];
          };
        }
        ../modules/options.nix
        (import ../modules/_hm-mirror.nix { osMine = rawMine identity; })
      ];
    }).config.mine;

  identityEl =
    mine:
    let
      email = if mine.user.email == null then "" else mine.user.email;
    in
    ''
      ;;; identity.el -*- lexical-binding: t; -*-
      ;; Generated by core.lib.mkDoomdir from mine.* — do not edit.

      (setq user-full-name ${builtins.toJSON mine.user.fullName})
      (setq user-mail-address ${builtins.toJSON email})
      (setq mine-hostname ${builtins.toJSON mine.hostName})
      (setq mine-username ${builtins.toJSON mine.user.username})
      (setq mine-full-name ${builtins.toJSON mine.user.fullName})
      (setq mine-email ${builtins.toJSON email})
    '';
in
{
  flake.lib.mkDoomdir =
    {
      system,
      hostname,
      coreDir ? (inputs.self + "/doom"),
      leafDir,
      identity ? [ ],
    }:
    let
      pkgs = inputs.nixpkgs.legacyPackages.${system};
      mine = resolvedMine identity;
    in
    pkgs.runCommand "doomdir-${hostname}" { } ''
      set -euo pipefail
      mkdir -p "$out"

      # Manifest: core init.el, then the leaf's init-extra.el appended (two
      # `doom!` blocks are idempotent — the last declaration of a module wins).
      cat ${coreDir}/init.el > "$out/init.el"
      if [ -e ${leafDir}/init-extra.el ]; then
        cat ${leafDir}/init-extra.el >> "$out/init.el"
      fi

      # config.el / packages.el are core copies whose trailing `load!` picks up
      # the leaf fragments copied alongside below.
      cp ${coreDir}/config.el "$out/config.el"
      cp ${coreDir}/packages.el "$out/packages.el"

      # Leaf fragments (always materialized so the trailers never fail).
      for f in config-extra.el packages-extra.el; do
        if [ -e ${leafDir}/"$f" ]; then
          cp ${leafDir}/"$f" "$out/$f"
        else
          : > "$out/$f"
        fi
      done

      # Module union: leaf modules overwrite core modules on name collision.
      if [ -d ${coreDir}/modules ]; then
        cp -r ${coreDir}/modules "$out/modules"
      fi
      if [ -d ${leafDir}/modules ]; then
        mkdir -p "$out/modules"
        cp -r ${leafDir}/modules/. "$out/modules"
      fi

      # Snippets: baked read-only; leaf overwrites core.
      if [ -d ${coreDir}/snippets ]; then
        cp -r ${coreDir}/snippets "$out/snippets"
      fi
      if [ -d ${leafDir}/snippets ]; then
        mkdir -p "$out/snippets"
        cp -r ${leafDir}/snippets/. "$out/snippets"
      fi

      # Generated identity.
      cat > "$out/identity.el" <<'DOOM_EOF'
      ${identityEl mine}
      DOOM_EOF
    '';
}
